### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by sveta-maker** [sveta-maker/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by seda-debug** [comment]
For me, wealth is a tool for achieving clearly defined goals.Your money should always work.It takes patience and enthusiasm to achieve your goals. Think big - but be realistic. Life is too short and work is too important to waste energy in an occupation that is neither enjoyable nor beneficial.
