### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by sveta-maker** [sveta-maker/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by seda-debug** [comment]
https://m.facebook.com/DonaldTrump/?locale2=ru_RU
https://www.instagram.com/realdonaldtrump/?hl=ru
Mar-a-Lago,Palm Beach, Florida, USA
