### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by sveta-maker** [sveta-maker/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by seda-debug** [comment]
He was born in New York City, to a builder and real estate developer Frederick Trump and his wife Mary McLeod. He was one of the five children.
He had his initial schooling in the Kew Forest School, Forest hills, New York. At the age of 13, his parents sent him to New York Military Academy (NYMA) in Upstate New York where he performed well, both socially and academically; emerging as a star athlete and student leader by the time he graduated in 1964.
He was at Fordham University for two years before joining the Wharton School of Finance at the University Of Pennsylvania, from where he graduated in economics in 1968.Business Career
He joined his father’s company, ‘Elizabeth Trump and Son’, while still in college. The company focused on middle-class rental housing in Brooklyn, Queens and Staten Island. He became deeply involved in the project and with a $500,000 investment, turned the 1200 unit apartment complex in Cincinnati with a 66 percent vacancy rate to 100 percent occupancy within two years.
In 1971, he moved to Studio apartment in Manhattan, New York and became involved with larger building projects. In the following year, he finalized first multi-million dollar real estate transaction with the sale of Swifton village in Cincinnati, Ohio.
In 1985, he bought Mar-a-lago estate in Palm beach, Florida and renovated the Barbizon hotel and 100 Central Park South.
In 1988, he bought the Plaza Hotel in New York City.
In 1989, he bought a fleet of Boeing 727 airplanes to form Trump air shuttle service. Unfortunately a helicopter crash killed three Trump casino executives which lead to big issue.
By 1989, poor business decisions left him unable to meet loan payments but he somehow financed the construction of his third casino, the $1 million Taj Mahal, with high-interest junk bonds. The increasing debt soon brought him to business bankruptcy.
In 1990, he regained his previous stable financial position and fame and opened the Trump Taj Mahal casino in Atlantic City. Soon he gained approval for Riverside south development of West Side rail yards.
In 1996, he got the ownership of Miss Universe Organization which produces the Miss Universe, Miss USA, and Miss Tean USA pageants.
In 2003, he became joint partner with the National Broadcasting Company (NBC) where he became the executive producer and host of the NBC reality show, ‘The Apprentice’ which became a huge success. Following its success, he co-produced a show, ‘The Celebrity Apprentice’ along with British TV producer Mark Burnett.
Continue Reading Below
On October 21, 2004, Trump Hotels and Casino & Resorts declared a restructuring of its debt which led to a reduction in his individual ownership from 56 percent to 27 percent. The company applied for Chapter 11 Protection in November and soon the company re-emerged from bankruptcy as ‘Trump Entertainment Resorts Holdings’.
He marketed the Trump name on large number of products, including ‘Trump Financial’, ‘Trump Sales and Leasing’, ‘Trump Entrepreneur initiative’, ‘Trump Restaurants’, ‘Go TRUMP’, ‘Donald J. Trump signature collection’, etc. Moreover, he also received $1.5 million for every one-hour presentation he did for ‘The Learning Annex’. He also has a business simulation game called ‘Donald Trump’s Real Estate Tycoon’.Political Career
Trump also harbored political aspirations. In the 2000 elections he expressed his wish to run as a third-party candidate for the US presidency. In 2004 and 2008, he speculated about running for president in the Republican Party and in between in 2006, he considered running for governor of New York as a representative of the party. He again registered as a Republican in 2009 after having registered with the Democratic Party in 2001 and campaigned for it.
In 2010-2012, his involvement in politics intensified when he publicly announced his consideration of candidature for presidency again. However, his association with the ‘Birther issue’, a group that firmly believed Barack Obama was not born in the US, disparaged his political reputation. But he continued to be against Obama on various political issues.
In January 2013, he endorsed Israeli Prime Minister Benjamin Netanyahu during the Israeli elections. He was also a featured speaker at the 2013 Conservative Political Action Conference (CPAC).he managed to emerge victorious in the general election on November 8, 2016 in which he defeated Hillary Clinton to become the President of the United States.
Donald Trump assumed office as the 45th President of the United States of America on January 20, 2017.2020 U.S. Presidential Election
Donald Trump lost his bid for re-election when he lost to Democrat candidate Joe Biden in a bitterly fought election.

Major Works
In 1974, he obtained the option to buy two rail yards in New York City and after few years with the help of 40-year tax abatement from the government, he bought and turned the bankrupt Commodore Hotel into the Grand Hyatt and also created the ‘Trump organization’.
In 1980, he undertook the project of constructing the Wollman Rink in Central Park and completed it in six months using $750,000 of the remaining $3 million budget. In the same year, he renovated the Trump tower in New York City and Atlantic City casino business which led to huge debt.
In 2001, he completed the Trump world tower, which was a 72-storey residential tower across the UN headquarters. He also began construction on Trump plaza along the Hudson River.
In 2006, he bought the Menie estate in Balmadie, Aberdeen shire, Scotland to create the best golf course in the world on a site of special scientific interest (SSS) but it was met with criticism from environmentalists and by local landowners. But the battle became more difficult this year when the Scottish government approved the construction of a wind farm nearby.
He has hosted many wrestle mania events in Trump Plaza and has been an active participant in several of the shows. On June 15, 2009 he bought the WWE RAW show from WWE owner Vince McMohan.
