### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by sveta-maker** [sveta-maker/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by seda-debug** [comment]
Donald Trump is an ardent golf fan. He is so passionate about the sport that he even installed a golf simulator at the White House. Trump enjoys mixed martial arts and attending fights. Collecting paintings is among the Trump's unusual hobbies. At the same time, Trump collects works in which he himself is depicted in some kind of heroic or simply positive guise.Loves films, especially to act in them. Trump played several cameo roles in films. In particular, he starred in the movie "Home Alone 2". Trump has also appeared on numerous TV shows and even hosted the "Candidate" program.
